FROM ubuntu
MAINTAINER Eduardo Hattori <eduardo.hattori@hotmail.com>

RUN apt-get update \		
  	&& apt-get install -y curl  \
  	&& apt-get install -y nano  \
  	&& apt-get install -y nginx

RUN ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//'

RUN service nginx restart

EXPOSE 8080
